// Generated by CoffeeScript 1.6.3
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  this.HierarchyView = (function() {
    function HierarchyView(selector, args) {
      var defaults, name, value, _base;
      this.selector = selector;
      this.args = args != null ? args : {};
      this.toogle_sub_list = __bind(this.toogle_sub_list, this);
      defaults = {
        hide_time: 400,
        show_time: 400,
        hierarchy_view_title_selector: 'a'
      };
      for (name in defaults) {
        value = defaults[name];
        if ((_base = this.args)[name] == null) {
          _base[name] = value;
        }
      }
      this.list = $(this.selector);
      $(this.args.hierarchy_view_title_selector, this.list).click(this.toogle_sub_list);
    }

    HierarchyView.prototype.toogle_sub_list = function(event) {
      var sub_list, t;
      t = $(event.target);
      if (!t.is(this.args.hierarchy_view_title_selector)) {
        t = t.parents(this.args.hierarchy_view_title_selector);
      }
      sub_list = t.siblings('ul');
      if (sub_list.is(":visible")) {
        return sub_list.hide(this.args.hide_time);
      } else {
        return sub_list.show(this.args.show_time);
      }
    };

    return HierarchyView;

  })();

}).call(this);
